### ISSUE TITLE
Question on YZLFusion implementation

### ISSUE THREAD

**Issue by zehuichen123** [AndyYuan96/YZLFusion#1]
Hi, congratulate to YZLFusion getting great performance on nuScenes dataset. 
I wonder that do you conduct cross-modal GT-Paste for YZLFusion? Or simply follows the fade strategy similar to TransFusion (so that no need for GT-Paste)? Besides, are you going to release a paper for YZLFusion?
Thanks!

**Comment by AndyYuan96** [comment]
> Hi, congratulate to YZLFusion getting great performance on nuScenes dataset. I wonder that do you conduct cross-modal GT-Paste for YZLFusion? Or simply follows the fade strategy similar to TransFusion (so that no need for GT-Paste)? Besides, are you going to release a paper for YZLFusion? Thanks!

cross-modal GT-Paste : No.
fade strategy: lidar branch pretrain yes, for fusion training, no gtaug.
paper: maybe, I'm busy with company things, optimize this method and deploy this method to chip，and the method is really very simple and friendly to chip, but did have great performance, and I think for now the novelty is not enough, the name is just for fun🤣。

**Comment by zehuichen123** [comment]
I see~ Thanks for your kind answer!
