### ISSUE TITLE
About model ensemble

### ISSUE THREAD

**Issue by zwei-lin** [AndyYuan96/YZLFusion#4]
Hi,
    Thanks for the great work! 
    I find that YZLFusion improves NDS by ~2.0 when using the model ensemble strategy, which is a large improvement. I also tried to ensemble some models, including centerpoint, transfusion-L, and transfusion-LC. However, the performance is not good as expected (~0.5NDS improvement).
    What models do you choose? Do you only use two models for the ensemble (1. larger backbone 2. models with TTA), as mentioned in the Nuscene Ensemble Model Performance Section? Does a single model with a larger backbone achieve better results than an normal size backbone?
    Looking forward to your reply!

**Comment by AndyYuan96** [comment]
> 

I just follow centerpoint’s paper，no other special trick。
